### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [joneug/mdal-extension#11]
Hey @joneug,

Are you interested in demoing your VSCode extension in a [Areopa](https://areopa.academy/) webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

**Comment by joneug** [comment]
Thanks for reaching out! I will send you an email.
